name: Build and push Docker image on tag

on:
  push:
    tags:
      - 'be-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract branch/tag name
        id: extract_tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/be-}" >> "$GITHUB_OUTPUT"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ywallis/oweyeah-be:${{ steps.extract_tag.outputs.TAG }}
          file: ./docker/Dockerfile
