name: CI for backend

on: 
  push:
    branches: [backend_dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.7.8


      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked 

      - name: Run tests
        run: uv run pytest

      - name: Check formatting with black
        run: uv run black --check src
